[build]
	command = "pnpm run build"
	commandOrigin= "config"
	environment= { POSTGRES_PRISMA_URL="postgres://default:KO2DUzVhlAk0@ep-wandering-bird-a1oobesy-pooler.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require&pgbouncer=true&connect_timeout=15", POSTGRES_URL_NON_POOLING="postgres://default:KO2DUzVhlAk0@ep-wandering-bird-a1oobesy.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require" }
	publish= "/opt/build/repo/build"
	publishOrigin= "config"